const colors = require('tailwindcss/colors')

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    spacing: {
        px: '1px',
        0: '0',
        0.25: '0.25rem',
        0.5: '0.5rem',
        1: '1rem',
        1.5: '1.5rem',
        2: '2rem',
        2.5: '2.5rem',
        3: '3rem',
        3.5: '3.5rem',
        4: '4rem',
        5: '5rem',
        6: '6rem',
        7: '7rem',
        8: '8rem',
        9: '9rem',
        10: '10rem',
        11: '11rem',
        12: '12rem',
        14: '14rem',
        16: '16rem',
        20: '20rem',
        24: '24rem',
        28: '28rem',
        32: '32rem',
        36: '36rem',
        40: '40rem',
        44: '44rem',
    },
    sizes: {
        px: '1px',
        0: '0',
        0.25: '0.25rem',
        0.5: '0.5rem',
        1: '1rem',
        1.5: '1.5rem',
        2: '2rem',
        2.5: '2.5rem',
        3: '3rem',
        3.5: '3.5rem',
        4: '4rem',
        5: '5rem',
        6: '6rem',
        7: '7rem',
        8: '8rem',
        9: '9rem',
        10: '10rem',
        11: '11rem',
        12: '12rem',
        14: '14rem',
        16: '16rem',
        20: '20rem',
        24: '24rem',
        28: '28rem',
        32: '32rem',
        36: '36rem',
        40: '40rem',
        44: '44rem',
    },
    colors: {
        primary: {
            base: '#9A9779',
            fade: '#EFEDD8',
            neutral: '#F1F0EA'
        },
        royal: {
            base: '#455379',
            fade: '#CFD8EE',
            neutral: '#EBEDF3'
        },
        blood: {
            base: '#7C3305',
            fade: '#EFDACC',
            neutral: '#F3EEEC'
        },
        neutral: {
            0: '#222222',
            1: '#676363',
            2: '#A5A1A1',
            3: '#CACAC9',
            4: '#E9E9E9'
        },
        white: colors.white,
        gray: colors.coolGray,
        blue: colors.lightBlue,
        red: colors.rose,
        pink: colors.fuchsia,
    },
    fontFamily: {
        logo: ['Trajan Pro', 'serif'],
        title: ['Didot', 'serif'],
        heading: ['Optima', 'serif'],
        body: ['Gill Sans', 'sans-serif'],
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
  ],
}
